# Generated by Django 4.0.2 on 2022-02-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='registered_dttm',
        ),
    ]
