# Generated by Django 4.0.2 on 2022-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_registered_dttm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Compass tag', 'verbose_name_plural': 'Compass tags'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, verbose_name='tag name'),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='compass_tag',
        ),
    ]
