# Generated by Django 4.0.2 on 2022-02-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '패스트캠퍼스 사용자', 'verbose_name_plural': '패스트캠퍼스 사용자'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=64, verbose_name='이메일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='password',
            field=models.CharField(max_length=64, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='username',
            field=models.CharField(max_length=64, verbose_name='사용자'),
        ),
    ]
