# Generated by Django 4.0.2 on 2022-02-25 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_alter_fcuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': 'compass user', 'verbose_name_plural': 'compass users'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='firstname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcuser',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='lastname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(max_length=64, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='username',
            field=models.CharField(max_length=64, verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='fcuser',
            table='compass_user',
        ),
    ]
