# Generated by Django 4.0.2 on 2022-02-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_alter_tag_options_alter_tag_name_alter_tag_table'),
        ('fcuser', '0004_alter_fcuser_options_fcuser_firstname_and_more'),
        ('board', '0002_board_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'compass ask board', 'verbose_name_plural': 'compass ask boards'},
        ),
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.TextField(verbose_name='Contents'),
        ),
        migrations.AlterField(
            model_name='board',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Written Date'),
        ),
        migrations.AlterField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcuser.fcuser', verbose_name='Writer'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='compass_ask_board',
        ),
    ]
